Repository clj-commons/aleph, pull requests merged in 2020-08, with the labels that each got.

#472 Get rid of `:max-chunk-size` both for HTTP server and client
  src/aleph/http.clj
  src/aleph/http/client.clj
  src/aleph/http/server.clj
Labels: 1.0, netty & internals

#508 Introduce activity logger configuration for the server
  src/aleph/http.clj
  src/aleph/http/server.clj
  src/aleph/netty.clj
  src/aleph/tcp.clj
Labels: 1.0, approved

#473 HTTP client to support body decompression
  README.md
  src/aleph/http.clj
  src/aleph/http/client.clj
  src/aleph/http/core.clj
  test/aleph/http_test.clj
Labels: 1.0, approved

#480 KQueue support
  project.clj
  src/aleph/http.clj
  src/aleph/http/client.clj
  src/aleph/http/server.clj
  src/aleph/netty.clj
  src/aleph/tcp.clj
  src/aleph/udp.clj
  test/aleph/http_test.clj
  test/aleph/tcp_test.clj
  test/aleph/udp_test.clj
  test/aleph/websocket_test.clj
Labels: 1.0

#546 Improved SSL handlers
  src/aleph/http.clj
  src/aleph/http/client.clj
  src/aleph/http/core.clj
  src/aleph/http/server.clj
  src/aleph/netty.clj
  test/aleph/tcp_ssl_test.clj
Labels: 1.0

#422 Handle WebSocket handshake timeouts
  src/aleph/http.clj
  src/aleph/http/client.clj
  src/aleph/utils/WebSocketHandshakeTimeoutException.java
  test/aleph/websocket_test.clj
Labels: 1.0, approved

#432 Attempt to provide correct API for multipart resources management
  src/aleph/http/multipart.clj
  test/aleph/http/multipart_test.clj
Labels: 1.0

#488 Custom DNS resolver and proxy support for WebSocket clients.
  src/aleph/http.clj
  src/aleph/http/client.clj
Labels: 1.0

#471 Catch FileNotFoundException when sending file body
  src/aleph/http/core.clj
  src/aleph/http/server.clj
  test/aleph/http_test.clj
Labels: 1.0

#528 Handle 308 Permanent Redirect (same behaviour than for 307)
  src/aleph/http/client_middleware.clj
Labels: clj-http parity
